# Generated by Django 4.2.11 on 2024-04-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_userprofile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_kcal',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
